import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.join(here, '..', 'output');
const outputFile = path.join(outputDir, 'testset-beauty-hair-nail.json');

const rawSources: Array<{
  url: string;
  bucket: string;
  title: string;
  topic: string;
  use_case: string;
  intent: string;
  language: string;
  region: string;
  tags: string[];
  content_type?: string;
}> = [
  {
    url: 'https://www.cosmopolitan.com.hk/cosmobody/partridge-soup-recipe-recommendations',
    bucket: 'wellness',
    title: 'Partridge soup recipe recommendations',
    topic: 'soup recipe roundup',
    use_case: 'recipe-summary',
    intent: 'summarization',
    language: 'zh-HK',
    region: 'HK',
    tags: ['soup', 'wellness', 'body-care'],
  },
  {
    url: 'https://www.womenshealthmag.com/tw/beauty/hair/g62835899/2025-girl-hairstyle/',
    bucket: 'hair',
    title: '2025 girl hairstyle roundup',
    topic: 'hair trend 2025',
    use_case: 'style-trend',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'trend', '2025'],
  },
  {
    url: 'https://pandafishtravel.tw/world_travel/archives/6839/',
    bucket: 'travel-lifestyle',
    title: 'Travel article (pandafishtravel)',
    topic: 'travel lifestyle',
    use_case: 'travel-summary',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['travel', 'lifestyle'],
  },
  {
    url: 'https://www.harpersbazaar.com/tw/beauty/hair/g62040390/2025-hair-styles/',
    bucket: 'hair',
    title: '2025 hair styles',
    topic: 'hair trend 2025',
    use_case: 'style-trend',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'trend', '2025'],
  },
  {
    url: 'https://www.elle.com/tw/beauty/news/g65456238/olive-young-2025-top15-new/',
    bucket: 'product-guide',
    title: 'Olive Young 2025 top 15 new items',
    topic: 'olive young product picks',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['olive-young', 'shopping', 'product-list'],
  },
  {
    url: 'https://www.round2hairsalon.com.tw/news-detail/5-wolf-tail-hairstyles/',
    bucket: 'hair',
    title: '5 wolf tail hairstyles',
    topic: 'wolf cut variants',
    use_case: 'style-howto',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'wolf-cut', 'tutorial'],
  },
  {
    url: 'https://www.marieclaire.com.tw/beauty/perfume-and-nails/88121',
    bucket: 'nail',
    title: 'Perfume and nail feature (88121)',
    topic: 'nail and scent roundup',
    use_case: 'trend-roundup',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'perfume', 'beauty'],
  },
  {
    url: 'https://allaspect.tw/article/2025-man-hair-top10',
    bucket: 'hair',
    title: '2025 men hair top 10',
    topic: 'men hair trend',
    use_case: 'style-trend',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'men', 'trend'],
  },
  {
    url: 'https://www.vogue.com.tw/beauty/article/%E5%85%89%E7%99%82%E7%BE%8E%E7%94%B2%E6%8C%87%E7%94%B2%E6%B2%9B%E5%BF%85%E7%9F%A5%E7%9A%84%E7%A7%98%E8%A8%A3',
    bucket: 'nail',
    title: 'Gel nail basics (Vogue TW)',
    topic: 'gel nail how-to',
    use_case: 'howto',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'gel', 'howto'],
  },
  {
    url: 'https://www.perfectcorp.com/zh-tw/consumer/blog/hair/hairstyles-for-round-face-shape',
    bucket: 'hair',
    title: 'Hairstyles for round face shape',
    topic: 'hair by face shape',
    use_case: 'style-guide',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'face-shape', 'guide'],
  },
  {
    url: 'https://rakuraku-jp.com/blogs/news/whitening-tablets',
    bucket: 'health',
    title: 'Whitening tablets guide',
    topic: 'supplement overview',
    use_case: 'product-explainer',
    intent: 'safety-check',
    language: 'zh-TW',
    region: 'TW',
    tags: ['supplement', 'whitening', 'health'],
  },
  {
    url: 'https://www.commonhealth.com.tw/article/88999',
    bucket: 'health',
    title: 'CommonHealth article 88999',
    topic: 'health explainer (id 88999)',
    use_case: 'health-summary',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['health'],
  },
  {
    url: 'https://www.commonhealth.com.tw/article/87720',
    bucket: 'health',
    title: 'CommonHealth article 87720',
    topic: 'health explainer (id 87720)',
    use_case: 'health-summary',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['health'],
  },
  {
    url: 'https://www.marieclaire.com.tw/beauty/hair/84130',
    bucket: 'hair',
    title: 'Marie Claire hair feature (84130)',
    topic: 'hair feature',
    use_case: 'style-guide',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'feature'],
  },
  {
    url: 'https://www.beauty321.com/post/66710',
    bucket: 'beauty-general',
    title: 'Beauty321 feature (66710)',
    topic: 'beauty feature',
    use_case: 'general-beauty',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['beauty'],
  },
  {
    url: 'https://www.harpersbazaar.com/tw/beauty/nail-design/g33989797/french-nail-collection/',
    bucket: 'nail',
    title: 'French nail collection',
    topic: 'french nail designs',
    use_case: 'trend-roundup',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'french', 'design'],
  },
  {
    url: 'https://www.cosmopolitan.com.hk/beauty/gel-nail-hot-trends',
    bucket: 'nail',
    title: 'Gel nail hot trends',
    topic: 'gel nail trends',
    use_case: 'trend-roundup',
    intent: 'summarization',
    language: 'zh-HK',
    region: 'HK',
    tags: ['nail', 'gel', 'trend'],
  },
  {
    url: 'https://www.elle.com/tw/beauty/hair/g36495209/korean-hairstyle-for-mid-length-hair/',
    bucket: 'hair',
    title: 'Korean hairstyle for mid-length hair',
    topic: 'korean mid-length styles',
    use_case: 'style-guide',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'korean', 'mid-length'],
  },
  {
    url: 'https://www.elle.com.hk/beauty_and_health/10-style-tips-for-trendy-princess-cut-hairstyles-updated',
    bucket: 'hair',
    title: 'Princess cut hairstyle tips',
    topic: 'princess cut tips',
    use_case: 'style-howto',
    intent: 'summarization',
    language: 'zh-HK',
    region: 'HK',
    tags: ['hair', 'princess-cut', 'tips'],
  },
  {
    url: 'https://www.cosmopolitan.com/tw/beauty/make-up/g64708927/2025-feet-nail/',
    bucket: 'nail',
    title: '2025 toe nail ideas',
    topic: 'toe nail trends',
    use_case: 'trend-roundup',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'toe', 'trend'],
  },
  {
    url: 'https://www.pinterest.com/pin/1121537113433744041/',
    bucket: 'visual-reference',
    title: 'Pinterest pin 1121537113433744041',
    topic: 'visual reference',
    use_case: 'visual-reference',
    intent: 'image-grounding',
    language: 'en',
    region: 'global',
    tags: ['visual', 'inspiration'],
  },
  {
    url: 'https://www.beauty321.com/post/65398',
    bucket: 'beauty-general',
    title: 'Beauty321 feature (65398)',
    topic: 'beauty feature',
    use_case: 'general-beauty',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['beauty'],
  },
  {
    url: 'https://wandou.tw/olive-young/',
    bucket: 'product-guide',
    title: 'Olive Young shopping (wandou)',
    topic: 'olive young shopping',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['olive-young', 'shopping'],
  },
  {
    url: 'https://www.elle.com.hk/beauty_and_health/top-25-products-from-olive-young-new',
    bucket: 'product-guide',
    title: 'Top 25 products from Olive Young',
    topic: 'olive young product picks',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-HK',
    region: 'HK',
    tags: ['olive-young', 'shopping', 'top-list'],
  },
  {
    url: 'https://www.vogue.com.tw/article/%E7%84%A6%E7%B3%96%E6%A3%95%E7%BE%8E%E7%94%B2',
    bucket: 'nail',
    title: 'Caramel maple nail look',
    topic: 'nail color trend',
    use_case: 'trend-roundup',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'color', 'trend'],
  },
  {
    url: 'https://www.elle.com.hk/beauty_and_health/top-10-skin-whitening-pills-and-drinks-update',
    bucket: 'health',
    title: 'Top 10 skin whitening pills/drinks',
    topic: 'whitening supplements',
    use_case: 'product-roundup',
    intent: 'safety-check',
    language: 'zh-HK',
    region: 'HK',
    tags: ['whitening', 'supplement', 'product'],
  },
  {
    url: 'https://www.womenshealthmag.com/tw/beauty/g64118435/nailart/',
    bucket: 'nail',
    title: 'Nail art ideas (WH TW)',
    topic: 'nail art inspiration',
    use_case: 'trend-roundup',
    intent: 'rewrite-and-structure',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'art', 'trend'],
  },
  {
    url: 'https://tw.cyberlink.com/blog/photo-editing-tips/3187/women-hairstyle',
    bucket: 'hair',
    title: 'Women hairstyle (CyberLink)',
    topic: 'hair photo/guide',
    use_case: 'style-guide',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'guide'],
  },
  {
    url: 'https://www.funliday.com/posts/oliveyoung-essence-serum/',
    bucket: 'product-guide',
    title: 'OliveYoung essence serum picks',
    topic: 'essence/serum roundup',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['olive-young', 'serum', 'skincare'],
  },
  {
    url: 'https://canals.hair/article/wolf-cut-hairstyle-for-woman',
    bucket: 'hair',
    title: 'Wolf cut hairstyle for woman',
    topic: 'wolf cut guide',
    use_case: 'style-howto',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['hair', 'wolf-cut', 'guide'],
  },
  {
    url: 'https://www.followheart.com.tw/news/bulbous-nose/',
    bucket: 'face-shape',
    title: 'Bulbous nose explainer',
    topic: 'nose shape/beauty',
    use_case: 'face-shape-advice',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['face', 'nose-shape', 'beauty'],
  },
  {
    url: 'https://www.cosmopolitan.com.hk/beauty/french-nail-trend-styles-ideas',
    bucket: 'nail',
    title: 'French nail trend styles',
    topic: 'french nail ideas',
    use_case: 'trend-roundup',
    intent: 'summarization',
    language: 'zh-HK',
    region: 'HK',
    tags: ['nail', 'french', 'trend'],
  },
  {
    url: 'https://www.renunderwear.com/blogs/news/wireless-bra-brand',
    bucket: 'product-guide',
    title: 'Wireless bra brand roundup',
    topic: 'intimates product guide',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['intimates', 'product', 'bra'],
  },
  {
    url: 'https://www.marieclaire.com.tw/beauty/perfume-and-nails/82700',
    bucket: 'nail',
    title: 'Perfume and nail feature (82700)',
    topic: 'nail + perfume feature',
    use_case: 'trend-roundup',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['nail', 'perfume', 'beauty'],
  },
  {
    url: 'https://www.elle.com.hk/beauty_and_health/problem-of-hair-loss-and-best-foods-for-hair',
    bucket: 'hair',
    title: 'Hair loss and best foods',
    topic: 'hair loss care',
    use_case: 'care-advice',
    intent: 'summarization',
    language: 'zh-HK',
    region: 'HK',
    tags: ['hair', 'hair-loss', 'nutrition'],
  },
  {
    url: 'http://www.yusoo.com.tw/?dir=Physiognomy&web=type&e_class=eye',
    bucket: 'face-shape',
    title: 'Physiognomy eye types',
    topic: 'face/eye reading',
    use_case: 'face-shape-advice',
    intent: 'summarization',
    language: 'zh-TW',
    region: 'TW',
    tags: ['face', 'physiognomy', 'eye'],
  },
  {
    url: 'https://www.harpersbazaar.com/tw/beauty/makeup/g62326800/olive-young-must-buy/',
    bucket: 'product-guide',
    title: 'Olive Young must buy list',
    topic: 'olive young shopping',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['olive-young', 'shopping', 'makeup'],
  },
  {
    url: 'https://www.klook.com/zh-TW/blog/must-buy-products-from-olive-young/',
    bucket: 'product-guide',
    title: 'Klook must-buy products from Olive Young',
    topic: 'olive young shopping (klook)',
    use_case: 'shopping-guide',
    intent: 'product-roundup',
    language: 'zh-TW',
    region: 'TW',
    tags: ['olive-young', 'shopping', 'travel'],
  },
];

const cases = rawSources.map((item, index) => ({
  id: `case-${String(index + 1).padStart(3, '0')}`,
  url: item.url,
  domain: new URL(item.url).hostname,
  title: item.title,
  topic: item.topic,
  bucket: item.bucket,
  use_case: item.use_case,
  intent: item.intent,
  content_type: item.content_type || 'article',
  language: item.language || 'zh-TW',
  region: item.region || 'TW',
  tags: item.tags || [],
}));

const bucketSummary = cases.reduce((acc, { bucket }) => {
  acc[bucket] = (acc[bucket] || 0) + 1;
  return acc;
}, {} as Record<string, number>);

const dataset = {
  schema_version: '1.0.0',
  dataset_id: 'beauty-hair-nail-mini-v1',
  name: 'Beauty/Hair/Nail Mini Test Set',
  description:
    'Small zh-Hant-heavy test set of beauty, hair, nail, Olive Young shopping, and wellness URLs.',
  created_at: new Date().toISOString(),
  locale: ['zh-Hant'],
  total_cases: cases.length,
  bucket_summary: Object.entries(bucketSummary).map(([bucket, count]) => ({ bucket, count })),
  cases,
};

await mkdir(outputDir, { recursive: true });
await writeFile(outputFile, JSON.stringify(dataset, null, 2));
console.log(`Wrote ${cases.length} cases to ${outputFile}`);
