export interface KeywordData {
  token: string;
  count: number;
}

export interface FrequentWordsPlacementAnalysis {
  word: string;
  snippets: string[]; // The raw context snippets extracted from text
  plan: string[]; // The AI-generated action rules (max 3)
  exampleSentence?: string; // NEW: An example sentence extracted from the original text
  isSentenceStart?: boolean; // NEW: Mostly appears at the beginning of sentences
  isSentenceEnd?: boolean; // NEW: Mostly appears at the end of sentences
  isPrefix?: boolean; // NEW: Often acts as a prefix
  isSuffix?: boolean; // NEW: Often acts as a suffix
}

export interface SectionAnalysis {
  title: string;
  narrativePlan: string[]; // Specific writing instructions for this specific section
  coreQuestion?: string; // One-sentence core question this section must answer
  difficulty?: 'easy' | 'medium' | 'unclear'; // How hard it is to give a clear answer
  writingMode?: 'direct' | 'multi_solutions'; // Derived from difficulty (easy => direct; others => multi solutions)
  solutionAngles?: string[]; // Distinct solution paths for medium/unclear
  subheadings?: string[]; // Exact H3s (if any) under this H2 from the reference text
  subsections?: {
    // NEW: Structured data corresponding to subheadings
    title: string;
    keyFacts: string[];
  }[];
  keyFacts?: string[]; // Checklist-ready atomic facts for this section
  uspNotes?: string[]; // USP/賣點提示
  isChecklist?: boolean; // Should render as checklist/listicle
  suppress?: string[]; // Points to avoid in this section
  augment?: string[]; // Points to add/borrow into this section
  logicalFlow?: string; // NEW: The strategic narrative arc/logic chain for this section
  coreFocus?: string; // NEW: The primary emphasis or emotional hook for this section (傳達側重)
  sentenceStartFeatures?: string[]; // NEW: Characteristics of sentence beginnings in this section
  sentenceEndFeatures?: string[]; // NEW: Characteristics of sentence endings in this section
  instruction?: string; // NEW: Detailed writing instruction generated by specific prompt
  sourceCharCount?: number; // NEW: Character count of the source text for this section
}

export interface ReferenceAnalysis {
  h1Title?: string; // NEW: H1 title extracted from reference
  introText?: string; // NEW: Intro paragraph after H1
  structure: SectionAnalysis[]; // Detailed structure with plans
  generalPlan: string[]; // Global style rules
  conversionPlan: string[]; // NEW: How the author presents value/benefits
  keyInformationPoints: string[]; // General High density facts/concepts
  brandExclusivePoints: string[]; // NEW: Unique Selling Points / Brand specific claims
  replacementRules?: string[]; // Deprecated: Old generic rules
  regionalReplacements?: { original: string; replacement: string; reason?: string }[]; // NEW: Automated regional fixes
  competitorBrands?: string[]; // Specific brand names to nuke
  competitorProducts?: string[]; // Specific product names to swap

  // NEW: Voice Strategy Enhancements
  regionVoiceDetect?: string; // Percentage composition (e.g., "70% HK / 30% TW")
  humanWritingVoice?: string; // Reasoning for why it sounds human-written

  // Detailed Voice Metrics
  toneSensation?: string; // 語感 (Tone/Voice vibe)
  entryPoint?: string; // 切入點 (Angle/Entry point)

  // Synthesis Metadata
  isSynthesis?: boolean;
  sourceCount?: number;
}

export interface AuthorityAnalysis {
  relevantTerms: string[]; // Filtered high-relevance terms
  combinations: string[]; // 3 Strategic ways to combine these terms
}

export type TargetAudience = 'zh-TW' | 'zh-HK' | 'zh-MY';

// NEW: Product / CTA Configuration
export interface ProductBrief {
  brandName: string; // The Entity (e.g., "TopGlow")
  productName: string; // The Full Item (e.g., "TopGlow 755nm Ultra Pulse")
  usp: string;
  ctaLink: string;
  targetPainPoints?: string; // Optional user input
}

// NEW: AI-Generated Mapping for Level 1 Injection
export interface ProblemProductMapping {
  painPoint: string;
  productFeature: string;
  relevanceKeywords: string[]; // Keywords to match against section titles
}

export interface SavedProfile {
  id: string;
  name: string;
  websiteType: string;
  authorityTerms: string;
  brandKnowledge?: string;
  targetAudience: TargetAudience;
  productBrief?: ProductBrief; // Deprecated in UI, kept for backward compat
  productRawText?: string; // NEW: The single source of truth for UI
  siteUrl?: string; // NEW: The domain or subfolder for this site profile
  brandRagUrl?: string; // NEW: Link to external RAG knowledge base
}

export interface PageProfile {
  id: string;
  name: string;
  title: string;
  referenceContent: string;
  scrapedImages?: ScrapedImage[];
  websiteType?: string;
  authorityTerms?: string;
  targetAudience: TargetAudience;
  brandRagUrl?: string; // NEW: Snapshotted link
}

export interface ScrapedImage {
  id?: string;
  url?: string; // NEW: Capture source URL for analysis/display
  altText: string;
  preContext: string;
  postContext: string;
  aiDescription?: string; // NEW: Stores the understanding from Gemini
  ignored?: boolean; // NEW: Allow UI to ignore individual images
}

export interface ImageAssetPlan {
  id: string;
  originalAlt?: string;
  category?: string;
  generatedPrompt: string;
  insertAfter: string;
  status: 'idle' | 'generating' | 'done' | 'error';
  url?: string;
  modelAppearance?: 'Asian' | 'Caucasian' | 'Latino' | 'Black';
  designStyle?: 'Photorealistic' | 'Digital Art' | 'Minimalist' | 'Corporate';
}

export interface VisualProfile {
  id: string;
  name: string;
  modelAppearance: string;
  designStyle: string;
}

export interface ArticleConfig {
  title: string;
  referenceContent: string;
  sampleOutline?: string;
  websiteType?: string;
  authorityTerms?: string;
  brandKnowledge?: string;
  targetAudience: TargetAudience;
  scrapedImages?: ScrapedImage[];
  useRag?: boolean;
  autoImagePlan?: boolean;

  productBrief?: ProductBrief; // Structured data (Passed to generator)
  productRawText?: string; // Raw input (Passed from UI)

  // Derived data passed to the generator
  keywordPlans?: FrequentWordsPlacementAnalysis[];
  referenceAnalysis?: ReferenceAnalysis;
  authorityAnalysis?: AuthorityAnalysis;
  productMapping?: ProblemProductMapping[]; // NEW: The logic map

  // NEW: The Visual Identity
  visualStyle?: string;
  writingStyle?: string;
}

export type GenerationStatus =
  | 'idle'
  | 'analyzing'
  | 'analysis_ready'
  | 'planning_visuals'
  | 'streaming'
  | 'completed'
  | 'error';

export type GenerationStep =
  | 'idle'
  | 'fetching_url'
  | 'parsing_product'
  | 'nlp_analysis'
  | 'extracting_structure'
  | 'analyzing_visuals'
  | 'analyzing_authority'
  | 'planning_keywords'
  | 'mapping_product'
  | 'writing_content'
  | 'refining_headings'
  | 'generating_images'
  | 'localizing_hk'
  | 'finalizing';

// --- Cost Tracking Types ---

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

export interface CostBreakdown {
  inputCost: number;
  outputCost: number;
  totalCost: number;
}

export interface AIRequestConfig {
  responseMimeType?: string;
  responseSchema?: any;
  temperature?: number;
  topK?: number;
  topP?: number;
  providerOptions?: {
    vertex?: {
      useSearchGrounding?: boolean;
      groundingConfig?: {
        googleSearchRetrieval?: Record<string, unknown>;
      };
    };
  };
}

export interface AIResponse {
  text: string;
  object?: any;
  usageMetadata?: any;
  candidates?: any[];
}

export interface ServiceResponse<T> {
  data: T;
  usage: TokenUsage;
  cost: CostBreakdown;
  duration?: number; // NEW: Execution time in ms
}

export interface ContentScore {
  value: number; // 0-100
  label: string; // Poor, Good, Excellent
  color: string; // tailwind color class
}

// NEW: Tracking injection in individual sections
export interface SectionGenerationResult {
  title: string; // Section title
  content: string; // Final content (chosen or default)
  rawContent?: string; // Original first-pass draft
  refinedContent?: string; // Second-pass refined version
  usedPoints: string[];
  injectedCount: number; // Number of times product was mentioned
}

export interface HeadingOption {
  text: string;
  reason?: string;
  score?: number;
}

export interface HeadingH3 {
  h3_before: string;
  h3_after: string;
  h3_reason?: string;
}

export interface HeadingResult {
  before: string;
  after: string;
  h2_before: string;
  h2_after: string;
  h2_reason?: string;
  h2_options?: HeadingOption[];
  h3?: HeadingH3[];
  needs_manual?: boolean;
}
export interface AnalysisDocument {
  id: string;
  timestamp: number;
  title: string;
  keywordPlans: FrequentWordsPlacementAnalysis[];
  refAnalysis: ReferenceAnalysis | null;
  authAnalysis: AuthorityAnalysis | null;
  visualStyle: string;
  productMapping: ProblemProductMapping[];
  productBrief: ProductBrief | undefined;
  targetAudience: TargetAudience;
  languageInstruction: string;
  sourceContent?: string;
  brandRagUrl?: string; // NEW: Link to external RAG
}
